Repository bpftrace/bpftrace, pull requests merged in 2020-04, with the labels that each got.

#1200 Update minimum required version of CMake to 3.8
  CMakeLists.txt
Labels: do-not-merge

#1280 Move CI over to GH actions
  .github/workflows/ci.yml
  .travis.yml
Labels: build

#1288 Add LGTM static analyzer
  .lgtm.yml
Labels: build

#1284 Install C++17 compatible compiler on xenial embedded builds
  docker/Dockerfile.ubuntu-glibc
  src/ast/async_event_types.h
  tests/runtime/engine/utils.py
Labels: build

#1294 Printer print ast after semantic analysis
  src/ast/printer.cpp
  src/ast/printer.h
  src/main.cpp
Labels: RFC
